### ISSUE TITLE
Activate only when filename ends with `.user.js` or document contains `// ==UserScript==`

### ISSUE THREAD

**Issue by Araxeus** [andywang425/vscode-scriptmonkey#11]
I think by default, each provider should only activate if the current document filename ends with `.user.js`
then there should be an extension option to activate if the current document text contains `// ==UserScript==`

Maybe each provider could call a function like this? 

```ts
function checkIfShouldRun(document: vscode.TextDocument, shouldSearchDocument: boolean): boolean {
    if (document.fileName.endsWith(".user.js")) {
        return true;
    }

    if (shouldSearchDocument || document.isUntitled) {
        const text = document.getText();
        return text.startsWith("// ==UserScript==") || text.includes(`${document.eol}// ==UserScript==`);
    }

    return false;
}
```

What do you think of this idea?

**Comment by bd-dxg** [comment]
Thank you very much for the author's development. I also have the same requirement. I expect the plug-in to take effect only in the file with the suffix '.user.js'

**Comment by andywang425** [comment]
That's a good idea. Maybe i can add an extension option like: Extension activate only  in the `.user.js` file. Or let users to choose the the file suffixes that they expect the extension to take effect. Checking if the current document text contains `//==UserScript==` may cause a little bit performance loss, i think checking the file suffix is enough.

**Comment by Araxeus** [comment]
> Checking if the current document text contains //==UserScript== may cause a little bit performance loss

My solution above only checks if one of the lines start with it, so it shouldn't matter much. And also it should be optional.
 

But most important is just some kind of way to control when it activates, since currently it pollutes any open js file

**Comment by andywang425** [comment]
`v0.0.7` has been published, check it out :)
However, syntax highlight still can't be controlled by extension settings due to the limitations of vscode, editing the `package.json` or `syntaxes/userjs.tmLanguage.json` file manually seems to be the only solution.

**Comment by Araxeus** [comment]
This is great! I can't even find the syntax highlighting you are talking of, so LGTM!

**Comment by Araxeus** [comment]
@andywang425 would still be cool to have an option so that the extension checks if the first written line starts with 
`// ==UserScript==`

https://github.com/andywang425/vscode-scriptmonkey/blob/d57794ab1b629d47e48a203bef7835e4c6d091c5/src/other/fileSuffixChecker.ts#L10-L18

```js
if (document.getText().trimStart().startsWith("// ==UserScript==")) {
    return true;
}
```

**Comment by andywang425** [comment]
> would still be cool to have an option so that the extension checks if the first written line starts with
// ==UserScript==

Just did some work in this [commit](https://github.com/andywang425/vscode-scriptmonkey/commit/6454ddb5edb1c440636898b9e6b8bb32858877e8). I planned to implement this feature in the next release.
