### ISSUE TITLE
Autocomplete/Suggestions don't work

### ISSUE THREAD

**Issue by matronator** [andywang425/vscode-scriptmonkey#13]
I thought it might be because of some conflict with another extension, but even on a clean profile with no extensions installed, the suggestions are not showing.

<img width="921" alt="Snímek obrazovky 2023-05-08 v 0 43 47" src="https://user-images.githubusercontent.com/5470780/236706079-5408b91d-141f-4742-94e4-efe218c86951.png">

**Comment by andywang425** [comment]
Yeah, it's not working. I thought maybe I made a mistake in the last update, but even the old version extension's autocomplete can't work too. Confusing bug.

**Comment by Askhento** [comment]
Same thing here, tried to disable all extension with only Scriptmonkey enabled with no luck((
