### ISSUE TITLE
Metadata autocomplete labels with @ symbol

### ISSUE THREAD

**Issue by jerone** [andywang425/vscode-scriptmonkey#18]
I find it confusing that the metadata autocomplete labels are missing their `@` symbol.

Before commit https://github.com/andywang425/vscode-scriptmonkey/commit/945764c63600f5856b63251dae8c92338867f9f2 they were part of the label, but removed for some reason.

![image](https://github.com/andywang425/vscode-scriptmonkey/assets/55841/10bf5bae-4ca3-4f53-a2ab-e1452334052c)

As you can see in above screenshot, the `@ts-*` autocompletions are prefixed with the `@` symbol.
Probably because of that, they get a higher sorting then Scriptmonkey autocompletions.

Another reason is that metadata like `name` are too generic and could be suggested by other extensions.

_Great extension 👍_

**Comment by andywang425** [comment]
Thanks for your feedback. I forget why i removed `@` from the labels, but i will bring it back in the next version.

**Comment by jerone** [comment]
I think it was [changed to make it the trigger](https://github.com/andywang425/vscode-scriptmonkey/commit/945764c63600f5856b63251dae8c92338867f9f2#diff-b1a30f52d3603d4e7c3f2761c79d965ee3b832eacbc59781bf15af9bc914da5aR35) for autocomplete, and with the label you would probably get double `@`-characters. Which makes sense.

You can however add the symbol back to the label and append an `innerText`-property without the symbol (as you've [already done](https://github.com/andywang425/vscode-scriptmonkey/blob/945764c63600f5856b63251dae8c92338867f9f2/src/providers/Completion/items/GMmetaCompletionItems.ts#L214C9-L214C19) for other items).

**Comment by andywang425** [comment]
My idea is to change the following line
https://github.com/andywang425/vscode-scriptmonkey/blob/945764c63600f5856b63251dae8c92338867f9f2/src/providers/Completion/GMmetaCompletionProvider.ts#L12

to this:
```ts
const completionItem = new vscode.CompletionItem('@' + item.label, item.kind);
```

By doing so,  we don't have to add a `innerText` property for each item.
