### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by NilsGke** [andywang425/vscode-scriptmonkey#22]
Hey, i'd love to use this extension but with typescript. 
Is there a way to make it possible?

**Comment by andywang425** [comment]
Implementing metadata highlight in typescript files should be easy, but other (completion, hover hints) features may require interaction with typescript language service or building our own language service, which will be a hard work.

I position this extension as a small tool for viewing userscript code and writing simple userscripts, hence it only supports javascript.

If you prefer writing userscripts in typescript, maybe you can try this <https://github.com/lisonge/vite-plugin-monkey>.

**Comment by NilsGke** [comment]
> If you prefer writing userscripts in typescript, maybe you can try this https://github.com/lisonge/vite-plugin-monkey.

Thats what i ended up using - thank you
