### ISSUE TITLE
Feature request: stored values for @namespace, @author

### ISSUE THREAD

**Issue by Kwack-Kwack** [andywang425/vscode-scriptmonkey#7]
Hey,

Loving the extension so far, it makes writing userscripts so much easier.

Would it be possible to have an __autofilled author key__ (customizable, rather than just "Your Name"), as well as automatically filling out __namespace keys__ with the same url per workspace/folder? Perhaps even the icon key as well?

First one would be very useful, second one is a bit more complex (and niche) but would help ease the repetition. Thanks.

**Comment by andywang425** [comment]
Thank you for your feedback. I will add this feature in the future release.

**Comment by andywang425** [comment]
> as well as automatically filling out namespace keys with the same url per workspace/folder?

I'll support this feature **globally** first rather than **per workspace/folder** since it's easier to implement and  I'm new to vscode extension development. Maybe this feature will support **per workspace/folder** after I learn more.

**Comment by andywang425** [comment]
I've just published a new release. Go and check it out.
