### ISSUE TITLE
CSS highlight in "addStyle"

### ISSUE THREAD

**Issue by onsamyj** [andywang425/vscode-scriptmonkey#9]
In "addStyle" CSS doesn’t get proper syntax highlight.

I use `` GM_addStyle(` `) ``, [there are other ways to do that](https://sourceforge.net/p/greasemonkey/wiki/GM_addStyle/), but I have not tested them.

**Comment by andywang425** [comment]
Are you looking for something like this? 
![image](https://user-images.githubusercontent.com/56548456/202489160-839c0686-cf49-433b-bf6d-9ff15605eef7.png)
That's a good idea. I'll try to implement this feature in a future release.

**Comment by onsamyj** [comment]
Exactly! Thank you :)

**Comment by andywang425** [comment]
Finally done, though it doesn't look as good as expected:
![](https://github.com/andywang425/vscode-scriptmonkey/raw/main/images/GM_addstyle.png)

**Comment by onsamyj** [comment]
Because it seems like it uses slightly different rules than regular CSS highlighting?

![Code_vgVU7yXyTg](https://user-images.githubusercontent.com/1064006/213459204-567a6071-d2c7-4852-997b-15c7270676d7.png)
← Userscript | plain CSS →

Anyway, I like it! But feel free to tinker some more if you want :)

**Comment by andywang425** [comment]
Thanks! Handling embedded languages is not easy. Maybe I will improve it in the future.  
I'm glad you like it :)
